### ISSUE TITLE
ImportError: No module named 'slogging'

### ISSUE THREAD

**Issue by cemsbr** [pipermerriam/ethereum-alarm-client#9]
I got this error after installing from pip and running "eth_alarm scheduler".

**Comment by pipermerriam** [comment]
Can you post a full stacktrace, python version, and operating system.

**Comment by cemsbr** [comment]
$ eth_alarm scheduler
Traceback (most recent call last):
  File "/usr/bin/eth_alarm", line 9, in <module>
    load_entry_point('ethereum-alarm-clock-client==7.0.0', 'console_scripts', 'eth_alarm')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/eth_alarm_client/__init__.py", line 2, in <module>
    from .call_contract import CallContract  # NOQA
  File "/usr/lib/python3.5/site-packages/eth_alarm_client/call_contract.py", line 12, in <module>
    from .contracts import (
  File "/usr/lib/python3.5/site-packages/eth_alarm_client/contracts.py", line 4, in <module>
    from populus.contracts import Contract
  File "/usr/lib/python3.5/site-packages/populus/contracts/__init__.py", line 2, in <module>
    from populus.contracts.utils import (  # NOQA
  File "/usr/lib/python3.5/site-packages/populus/contracts/utils.py", line 4, in <module>
    from ethereum import utils as ethereum_utils
  File "/usr/lib/python3.5/site-packages/ethereum/__init__.py", line 8, in <module>
    import slogging  # noqa
ImportError: No module named 'slogging'

$ python --version
Python 3.5.1
$ uname -a
Linux balanchine 4.5.4-1-ARCH #1 SMP PREEMPT Wed May 11 22:21:28 CEST 2016 x86_64 GNU/Linux

**Comment by pipermerriam** [comment]
Sorry for the month late reply.  This is because you're using python3.  Switch to python 2.7 and things should work.  Python3 support incoming but it may still be a while.

**Comment by cemsbr** [comment]
I installed it with ``pip2`` and now it is working. Thank you.
